# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R8wn0Lkgzaig_SmkZWNJH6Uc48BFQ-K6
"""



n = 4
for i in range(1,n+1):
  for j in range(i,4):
    print(" ",end="")
  for j in range(1,i+1):
    print("*",end=" ")
  print("")

n = 4
for i in range(4,0,-1):
  for j in range(i,4):
    print("-",end="")
  for j in range(1,i+1):
    print("*",end=" ")
  print("")

n = 4
for i in range(4,0,-1):
  for j in range(i,4):
    print(" ",end="")
  for j in range(1,i+1):
    print(j,end=" ")
  print("")

for i in range(1,5):
  for j in range(i,4):
    print("",end=" ")
  for j in range(1,i+1):
    print("*",end=" ")
  print("")

for i in range(4,0,-1):
  for j in range(i,4):
    print("",end=" ")
  for j in range(1,i+1):
    print("*",end=" ")
  print("")

for i in range(4,0,-1):
  for j in range(i,4):
    print(" ",end=" ")
  for j in range(1,i+1):
    print("*",end=" ")
  print("")
for i in range(2,5):
  for j in range(i,4):
    print(" ",end=" ")
  for j in range(1,i+1):
    print("*",end=" ")
  print("")

n = 4
for i in range(4,0,-1):
  for j in range(i,4):
    print("",end=" ")
  for j in range(1,i+1):
    print("*",end=" ")
  print("")
for i in range(2,5):
  for j in range(i,4):
    print("",end=" ")
  for j in range(1,i+1):
    print("*",end=" ")
  print("")

n = 4
x = 1
for i in range(1,n+1):
  for j in range(i,4):
    print("",end=" ")
  for j in range(1,i*2):
    print("*",end="")
  x+=1
  print("")

n = 4
x = 1
for i in range(1,n+1):
  for j in range(i,4):
    print(" ",end=" ")
  for j in range(1,i*2):
    if(j==1 or  i==4 or j==2*i-1):
      print("*",end=" ")
    else:
      print(" ",end=" ")
  x+=1
  print("")